### PR TITLE
Validate the email of new candidates.

### LINKED ISSUE #17: Validate email format upon registering candidates and voters
Currently, voters emails (which are used to send voting tokens) are not validated.
As a consequence, when we send voting tokens, we may crash (as the postal jar we use cannot handle that).
Realistically, we shouldn't allow for candidates or voters to have emails that are not even in a valid email format.

### PR DESCRIPTION
**Pull request by Kineolyan**
Reading again #17, I see that I omitted candidate email validation in PR #20.
This PR adds validation for that specific part.

Once again, the translation in Brazilian is missing. I prefer having a native speaker giving me the translation that using a random translation tool.

Closes: #17

### CODE REVIEW

File: resources/pt_BR.clj [hunk 1]
```diff
@@ -29,6 +29,7 @@
     :motivation "Motivação"
     :region "Região"
     :minibio "Minibio"
+    :invalid-email "Invalid email"
```
Comment (hugocorbucci) [inline resources/pt_BR.clj]: Email inválido

**Comment by hugocorbucci** [comment]
Added the translation :)
Looks good otherwise. Would be nice to set up some blackbox tests at some point... maybe some other time

**Comment by Kineolyan** [comment]
I agree with the black box testing. The current issue I see is that a lot is already wired, so testing the API would involved sending actual mails, ... It may require some refactoring not to do so.
I'll look at it in the coming days. If you have any idea or similar tests, please tell me.
